name: Build and upload to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        py: [3.10]
        include:
          - name: 'Linux'
            os: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup for cibuildwheel
        id: setup
        run: |
          echo "Setup commands for cibuildwheel."
          cp src/python/README.rst res/README.rst

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_BEFORE_ALL: "yum install -y freetype-devel.x86_64 mesa-libGLU-devel.x86_64 libxml2-devel.x86_64"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_ARCHS: "auto64"
        # valid inputs are ['package-dir', 'output-dir', 'config-file', 'only']
        with:
          package-dir: res

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

